version: '1.0'
services:
  user-service-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src 
  mysql_db:
    image: mysql
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=taskmgmt
      - MYSQL_DATABASE=task_mgmt_users
      - MYSQL_PASSWORD=taskmgmt
      - MYSQL_TCP_PORT=3307